VehicleInsuranceManagement/VehicleInsuranceManagement/Controllers/PurchaseInsuranceProcessesController.cs
using MoreLinq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using VehicleInsuranceManagement.Models;

namespace VehicleInsuranceManagement.Controllers
{
    public class PurchaseInsuranceProcessesController : Controller
    {
        private VehicleInsuranceEntities db = new VehicleInsuranceEntities();

        // GET: PurchaseInsuranceProcesses
        public ActionResult Index()
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public List<InsuranceType> GetInsurances()
        {
            List<InsuranceType> insurances = db.InsuranceTypes.ToList();
            return insurances;
        }

        public List<Coefficient> GetCoefficients()
        {
            List<Coefficient> coefficients = db.Coefficients.ToList();
            return coefficients;
        }

        public List<Vehicle> GetVehiclesByCustomerID(int customerID)
        {
            List<Vehicle> vehicles = (from v in db.Vehicles
                                      where v.CustomerID == customerID && v.Status == "Enable"
                                      select v).ToList();
            return vehicles;
        }


        public ActionResult _PartialEstimate()
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                dynamic mymodel = new ExpandoObject();
                mymodel.Vehicles = GetVehiclesByCustomerID((int)Session["CusID"]);
                mymodel.Coefficients = GetCoefficients();
                return PartialView("_PartialEstimate", mymodel);
            }
        }

        public ActionResult _PartialEstimateTable(double c)
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewData["Coefficient"] = c;
            return PartialView("_PartialEstimateTable", db.InsuranceTypes.ToList());
        }

        public ActionResult _PartialEstimateVehicleDetails(int? vehicleID)
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<Vehicle> vehicles = GetVehiclesByCustomerID((int)Session["CusID"]);
            List<VehicleModel> models = db.VehicleModels.ToList();
            var vehicleRecord = from v in vehicles
                                join m in models on v.VehicleModelID equals m.VehicleModelID into table1
                                from m in table1.ToList()
                                select new VehicleModelView
                                {
                                    vehicle = v,
                                    model = m
                                };
            VehicleModelView vehicle = vehicleRecord.FirstOrDefault(v => v.vehicle.VehicleID == vehicleID);
            return PartialView("_PartialEstimateVehicleDetails", vehicle);
        }

        public ActionResult _PartialInsuranceInfo(int? vehicleID)
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            dynamic mymodel = new ExpandoObject();
            mymodel.InsuranceTypes = GetInsurances();
            List<Vehicle> vehicles = GetVehiclesByCustomerID((int)Session["CusID"]);
            List<VehicleModel> models = db.VehicleModels.ToList();
            var vehicleRecord = from v in vehicles
                                join m in models on v.VehicleModelID equals m.VehicleModelID into table1
                                from m in table1.ToList()
                                select new VehicleModelView
                                {
                                    vehicle = v,
                                    model = m
                                };
            VehicleModelView vehicle = vehicleRecord.FirstOrDefault(v => v.vehicle.VehicleID == vehicleID);
            mymodel.Vehicle = vehicle;
            return PartialView("_PartialInsuranceInfo", mymodel);
        }

        public ActionResult _PartialPaymentInfo(int? vehicleID, int? insuranceID)
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            dynamic mymodel = new ExpandoObject();
            List<InsuranceType> insuranceTypes = GetInsurances();
            InsuranceType insuranceType = insuranceTypes.FirstOrDefault(i => i.InsuranceTypeID == insuranceID);
            mymodel.InsuranceType = insuranceType;
            List<Vehicle> vehicles = GetVehiclesByCustomerID((int)Session["CusID"]);
            List<VehicleModel> models = db.VehicleModels.ToList();
            var vehicleRecord = from v in vehicles
                                join m in models on v.VehicleModelID equals m.VehicleModelID into table1
                                from m in table1.ToList()
                                select new VehicleModelView
                                {
                                    vehicle = v,
                                    model = m
                                };
            VehicleModelView vehicle = vehicleRecord.FirstOrDefault(v => v.vehicle.VehicleID == vehicleID);
            mymodel.Vehicle = vehicle;
            return PartialView("_PartialPaymentInfo", mymodel);
        }

        public ActionResult _PartialOrderSummary(int? vehicleID, int? insuranceID)
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            dynamic mymodel = new ExpandoObject();
            List<InsuranceType> insuranceTypes = GetInsurances();
            InsuranceType insuranceType = insuranceTypes.FirstOrDefault(i => i.InsuranceTypeID == insuranceID);
            mymodel.InsuranceType = insuranceType;
            List<Vehicle> vehicles = GetVehiclesByCustomerID((int)Session["CusID"]);
            List<VehicleModel> models = db.VehicleModels.ToList();
            var vehicleRecord = from v in vehicles
                                join m in models on v.VehicleModelID equals m.VehicleModelID into table1
                                from m in table1.ToList()
                                select new VehicleModelView
                                {
                                    vehicle = v,
                                    model = m
                                };
            VehicleModelView vehicle = vehicleRecord.FirstOrDefault(v => v.vehicle.VehicleID == vehicleID);
            mymodel.Vehicle = vehicle;
            OrderPolicy orderPolicy = new OrderPolicy();
            mymodel.OrderPolicy = orderPolicy;
            List<Bill> bills = new List<Bill>();
            mymodel.Bills = bills;
            return PartialView("_PartialOrderSummary", mymodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _PartialOrderSummary([Bind(Include = "VehicleID,InsuranceTypeID,InsurancePrice,OrderDate,PolicyDate,PolicyDuration," +
            "PaymentType,Status")] OrderPolicy orderPolicy)
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var now = DateTime.Now;
            orderPolicy.OrderDate = now;
            orderPolicy.Status = "Enable";

            db.OrderPolicies.Add(orderPolicy);
            int count = int.Parse(Request.Form["count"]);
            decimal amount = Decimal.Parse(Request.Form["amount"]);
            for (int i = 0; i < count; i++)
            {
                Bill bill = new Bill();
                bill.OrderPolicy = orderPolicy;
                string s = Request.Form["Date-" + i];
                DateTime dt = DateTime.ParseExact(s, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                bill.ExpectedDate = dt;
                bill.Amount = amount;
                bill.Status = "Unpaid";
                db.Bills.Add(bill);
                db.SaveChanges();
            }

            db.SaveChanges();

            return Json(new { Success = true });
        }

        public ActionResult _PartialInvoice()
        {
            if (Session["CusID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int cusID = (int)Session["CusID"];
            dynamic mymodel = new ExpandoObject();
            OrderPolicy lastOrder = (from orders in db.OrderPolicies
                                     where orders.Vehicle.CustomerID == cusID
                                     select orders).ToList().LastOrDefault();
            List<Bill> lastOrderBills = (from b in db.Bills
                                         where b.OrderPolicy.PolicyNumber == lastOrder.PolicyNumber
                                         select b).ToList();

            Coefficient c = db.Coefficients.FirstOrDefault(v => v.SeatNumber == lastOrder.Vehicle.SeatNumber);

            mymodel.Bills = lastOrderBills;
            mymodel.OrderPolicy = lastOrder;
            mymodel.Coefficient = c;
            return PartialView("_PartialInvoice", mymodel);
        }

        public ActionResult _PartialInvoicePdf(int? id)
        {
            dynamic mymodel = new ExpandoObject();
            OrderPolicy lastOrder = (from orders in db.OrderPolicies
                                     where orders.Vehicle.CustomerID == id
                                     select orders).ToList().LastOrDefault();

VehicleInsuranceManagement/VehicleInsuranceManagement/Views/PurchaseInsuranceProcesses/Index.cshtml
@using System.Web;
@{
    ViewBag.Title = "Index";
}

<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0" style="background-image: url(../../img/carousel-bg-1.jpg);">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Get An Insurance</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Get An Insurance</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Service Start -->
<div class="container-xxl service py-5" id="purchaseInsurance">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="text-primary text-uppercase">// Our Services //</h6>
            <h1 class="mb-5">Get An Insurance</h1>
        </div>
        <div class="row g-4 wow fadeInUp" data-wow-delay="0.3s">
            <div class="col-lg-4">
                <div class="nav w-100 nav-pills me-4">
                    <button class="nav-link w-100 d-flex align-items-center text-start p-4 mb-4 active" disabled data-bs-toggle="pill" data-bs-target="#tab-pane-1" type="button">
                        <i class="fa fa-calculator fa-2x me-3"></i>
                        <h4 class="m-0">Estimate</h4>
                    </button>
                    <button class="nav-link w-100 d-flex align-items-center text-start p-4 mb-4" disabled data-bs-toggle="pill" data-bs-target="#tab-pane-2" type="button">
                        <i class="fa fa-car fa-2x me-3"></i>
                        <h4 class="m-0">Insurance Information</h4>
                    </button>
                    <button class="nav-link w-100 d-flex align-items-center text-start p-4 mb-4" disabled data-bs-toggle="pill" data-bs-target="#tab-pane-3" type="button">
                        <i class="fa fa-money-bill fa-2x me-3"></i>
                        <h4 class="m-0">Billing Information</h4>
                    </button>
                    <button class="nav-link w-100 d-flex align-items-center text-start p-4 mb-0" disabled data-bs-toggle="pill" data-bs-target="#tab-pane-4" type="button">
                        <i class="fa fa-list-alt fa-2x me-3"></i>
                        <h4 class="m-0">Order Summary</h4>
                    </button>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="tab-content w-100">
                    <div class="tab-pane fade show active" id="tab-insurance">
                        <div class="row g-4">
                            <div class="col-lg-12">
                                <div id="orderForm" class="bg-primary h-100 d-flex flex-column justify-content-center p-5 wow zoomIn customForm" data-wow-delay="0.2s">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Service End -->
<!-- The Modal -->
<div class="modal fade" id="insuranceModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title"></h4>
                <button type="button" class="close btnClose" onclick="closeModal();">×</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">

            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default btnHome" onclick="location.href='@Url.Action("Index", "Home")';">Go to Home</button>
                <button type="button" class="btn btn-default btnPrint" onclick="location.href='@Url.Action("PrintInvoice", "PurchaseInsuranceProcesses")';">Print</button>
                <button type="button" class="btn btn-dark btnClose" onclick="closeModal();">Close</button>
            </div>

        </div>
    </div>
</div>
<script>
    document.title = "Get An Insurance Page"
</script>

VehicleInsuranceManagement/VehicleInsuranceManagement/Views/PurchaseInsuranceProcesses/_PartialEstimate.cshtml
@using VehicleInsuranceManagement.Models
@model dynamic

<form id="estimate">
    <div class="form-group row">
        <label class="col-md-3 col-sm-4" for="vehicle" style="display: flex; align-items: center; padding-right: 6px;">Select a vehicle</label>
        <div class="col-md-9 col-sm-8">
            <select class="form-select col-9 border-0" id="vehicle" style="height: 55px;">
                <option selected disabled>--Select--</option>
                @foreach (Vehicle vehicle in Model.Vehicles)
                {
                    foreach (Coefficient c in Model.Coefficients)
                    {
                        if (c.SeatNumber == vehicle.SeatNumber)
                        {
                            <option id="@vehicle.VehicleID" value="@c.Coefficient1">@vehicle.VehicleNumber (Owner: @vehicle.VehicleOwnerName)</option>
                        }
                    }
                }
            </select>
        </div>
    </div>
    <div id="estimateVehicleDetails">

    </div>
    <div id="estimateTable">

    </div>
    <button class="btn btn-secondary w-100 py-3" style="margin-top: 1rem;" type="button">Continue</button>
</form>

VehicleInsuranceManagement/VehicleInsuranceManagement/Views/PurchaseInsuranceProcesses/_PartialEstimateTable.cshtml
@model IEnumerable<VehicleInsuranceManagement.Models.InsuranceType>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InsuranceTypeName)
            </th>
            <th style="text-align: center;">
                @Html.DisplayNameFor(model => model.Price) (USD/year)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.InsuranceTypeName)
                </td>
                <td class="text-right" style="text-align: center;">
                    @{
                        double price = Convert.ToDouble(item.Price);
                        double c = Convert.ToDouble(ViewData["Coefficient"]);
                        var insurancePrice = price + price * c;
                    }
                    @String.Format("{0:C}", insurancePrice)
                </td>
                <td style="text-align: right;">
                    @{
                        string[] separatingStrings = { "<div>", "</div>" };
                        string[] words = item.Description.Split(separatingStrings, System.StringSplitOptions.RemoveEmptyEntries);
                    }
                    <a data-toggle="popover" data-content="@words[0]" style="color: #D81324;">
                        <span class="fa fa-question-circle"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover({
            trigger: "hover",
            placement: "bottom",
            html: true,
            content: function () {
                return $(this).attr('data-content');
            }
        });
    });
</script>

VehicleInsuranceManagement/VehicleInsuranceManagement/Views/PurchaseInsuranceProcesses/_PartialEstimateVehicleDetails.cshtml
@model VehicleInsuranceManagement.Models.VehicleModelView

<table class="table" style="margin-top: 1rem;">
    <tbody>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.VehicleOwnerName)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.VehicleOwnerName)
            </td>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.VehicleNumber)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.VehicleNumber)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.VehicleType.VehicleTypeName)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.VehicleType.VehicleTypeName)
            </td>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.VehicleBodyNumber)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.VehicleBodyNumber)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.model.VehicleBrand.VehicleBrandName)
            </th>
            <td>
                @Html.DisplayFor(model => model.model.VehicleBrand.VehicleBrandName)
            </td>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.VehicleEngineNumber)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.VehicleEngineNumber)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.VehicleModel.VehicleModelName)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.VehicleModel.VehicleModelName)
            </td>
            <th>
                @Html.DisplayNameFor(model => model.vehicle.SeatNumber)
            </th>
            <td>
                @Html.DisplayFor(model => model.vehicle.SeatNumber)
            </td>
        </tr>
    </tbody>
</table>

VehicleInsuranceManagement/VehicleInsuranceManagement/Views/PurchaseInsuranceProcesses/_PartialInsuranceInfo.cshtml
@using VehicleInsuranceManagement.Models
@model dynamic

<form id="insuranceInfo">
    <div class="form-group row">
        <label class="col-md-3 col-sm-4" for="insurance" style="display: flex; align-items: center; padding-right: 6px;">Select an insurance</label>
        <div class="col-md-9 col-sm-8">
            <select class="form-select col-9 border-0" id="insurance" style="height: 55px;">
                <option selected disabled>--Select--</option>
                @foreach (InsuranceType insuranceType in Model.InsuranceTypes)
                {
                    double insurancePrice = (double)insuranceType.Price;
                    <option id="@insuranceType.InsuranceTypeID" value="@insurancePrice">@insuranceType.InsuranceTypeName</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group row" style="margin-top: 1.8rem; margin-bottom: 1.8rem;">
        <label class="col-md-3 col-sm-4" for="insuranceYear" style="display: flex; align-items: center; padding-right: 6px;">Number of years</label>
        <div class="col-md-9 col-sm-8" style="display: flex; align-items: center;">
            <div class="col-6">
                <label class="radio-inline" style="margin-right: 10px;">
                    <input type="radio" name="insuranceYear" value="1" checked>1 Year
                </label>
            </div>
            <div class="col-6">
                <label class="radio-inline" style="margin-left: 10px;">
                    <input type="radio" name="insuranceYear" value="2">2 Years
                </label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-sm-4" for="duration" style="display: flex; align-items: center; padding-right: 6px;">Duration</label>
        <div class="col-md-9 col-sm-8" style="display: flex; align-items: center;">
            <div class="col-6">
                <div class="date" id="date1" data-target-input="nearest">
                    <input type="text"
                           class="form-control border-0 datetimepicker-input"
                           placeholder="From" data-target="#date1" data-toggle="datetimepicker" style="height: 55px; background: #FFF">
                </div>
            </div>
            <div class="col-6">
                <div class="date" id="date2" data-target-input="nearest">
                    <input type="text"
                           class="form-control border-0 datetimepicker-input"
                           placeholder="To" data-target="#date2" data-toggle="datetimepicker" style="height: 55px; background: #FFF" readonly="">
                </div>
            </div>
        </div>
    </div>
    <div id="contentOrder" class="row">
        <hr>
        <div class="row selectedVehicle">
            <div class="col-md-3 col-sm-4 title">
                <span>Selected vehicle</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                @{
                    VehicleModelView v = Model.Vehicle;
                }
                <span>@v.model.VehicleBrand.VehicleBrandName - @v.model.VehicleModelName - @v.vehicle.VehicleOwnerName</span>
            </div>
        </div>
        <div class="row insurancePrice">
            <div class="col-md-3 col-sm-4 title">
                <span>Insurance price</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                <span></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button class="btn btn-secondary py-3 w-100 btnBack" style="margin-top: 1rem;" type="button">Back</button>
        </div>
        <div class="col">
            <button class="btn btn-secondary py-3 w-100 btnContinue" style="margin-top: 1rem; float: right" type="button">Continue</button>
        </div>
    </div>
</form>
<script>
    var today = new Date();
    today.setDate(today.getDate() + 1);

    $('.date').datetimepicker({
        format: 'L',
        minDate: new Date(today.getFullYear(), today.getMonth(), today.getDate())
    });
</script>

VehicleInsuranceManagement/VehicleInsuranceManagement/Views/PurchaseInsuranceProcesses/_PartialOrderSummary.cshtml
@using VehicleInsuranceManagement.Models
@model dynamic

@*<form id="paymentInfo">
    </form>*@

@using (Html.BeginForm("_PartialOrderSummary", "PurchaseInsuranceProcesses", FormMethod.Post, new { id = "orderSummary", }))
{
    @Html.AntiForgeryToken()
    var now = DateTime.Now.ToString("yyyy-MM-dd HH-mm-ss");
    <div id="billSchedule">

    </div>
    <input type="hidden" name="amount" class="amountPerPayment" />
    <input type="hidden" name="count" class="count" value="" />
    <div id="contentOrder" class="row">
        <div class="row selectedVehicle">
            <div class="col-md-3 col-sm-4 title">
                <span>Selected vehicle</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                @{
                    VehicleModelView v = Model.Vehicle;
                }
                <span>@v.model.VehicleBrand.VehicleBrandName - @v.model.VehicleModelName - @v.vehicle.VehicleOwnerName</span>
                @Html.Hidden("VehicleID", v.vehicle.VehicleID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="row selectedInsurance">
            <div class="col-md-3 col-sm-4 title">
                <span>Selected insurance</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                @{
                    InsuranceType i = Model.InsuranceType;
                }
                <span>@i.InsuranceTypeName</span>
                @Html.Hidden("InsuranceTypeID", i.InsuranceTypeID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="row insurancePrice">
            <div class="col-md-3 col-sm-4 title">
                <span>Insurance price</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                <span>@String.Format("{0:C}", @i.Price)</span>
                @Html.Hidden("InsurancePrice", i.Price, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="row insuranceDate">
            <div class="col-md-3 col-sm-4 title">
                <span>Insurance duration:</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                <span></span>
                @Html.Hidden("PolicyDate", null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.Hidden("PolicyDuration", null, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="row paymentType">
            <div class="col-md-3 col-sm-4 title">
                <span>Payment Type</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                <span></span>
                @Html.Hidden("PaymentType", null, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="row totalPrice">
            <div class="col-md-3 col-sm-4 title">
                <span>Total price</span>
            </div>
            <div class="col-md-9 col-sm-8 content">
                <span></span>
            </div>
        </div>
        <div class="row paymentSchedule">
            <h4>Payment Schedule</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="col-6">Payment date</th>
                        <th scope="col" class="col-6">Amount</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button class="btn btn-secondary py-3 w-100 btnBack" style="margin-top: 1rem;" type="button">Back</button>
        </div>
        <div class="col">
            <button class="btn btn-secondary py-3 w-100 btnBuy" style="margin-top: 1rem; float: right" type="button">Buy</button>
        </div>
    </div>
}