VehicleInsurance_Employee/VehicleInsurance_Employee/Models/VehicleBrand.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance_Employee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VehicleBrand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleBrand()
        {
            this.VehicleModels = new HashSet<VehicleModel>();
        }

        [Display(Name = "Brand ID")]
        public int VehicleBrandID { get; set; }

        [Display(Name = "Brand")]
        public string VehicleBrandName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleModel> VehicleModels { get; set; }
    }
}

VehicleInsurance_Employee/VehicleInsurance_Employee/Controllers/VehicleBrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VehicleInsurance_Employee.Models;

namespace VehicleInsurance_Employee.Controllers
{
    public class VehicleBrandsController : Controller
    {
        private VehicleInsuranceEntities db = new VehicleInsuranceEntities();

        // GET: VehicleBrands
        public ActionResult Index()
        {
            if (Session["EmpID"] != null)
            {
                return View(db.VehicleBrands.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // GET: VehicleBrands/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["EmpID"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                VehicleBrand vehicleBrand = db.VehicleBrands.Find(id);
                if (vehicleBrand == null)
                {
                    return HttpNotFound();
                }
                ViewBag.VehicleModel = db.VehicleModels.ToList();
                ViewBag.VehicleBrands = db.VehicleBrands.Find(id);
                ViewBag.VehicleModels = db.VehicleModels.Where(d => d.VehicleBrandID == id).FirstOrDefault();
                return View(vehicleBrand);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        public String VehicleModels(int id)
        {
            String name = "";
            VehicleModel vehicleModel = db.VehicleModels.Find(id);
            if (vehicleModel != null)
            {
                name = vehicleModel.VehicleModelName;
            }
            return name;
        }
        public String VehicleBrand(int id)
        {
            String name = "";
            VehicleModel vehicleModel = db.VehicleModels.Find(id);
            int idB = vehicleModel.VehicleBrandID;
            VehicleBrand br = db.VehicleBrands.Find(idB);
            name = br.VehicleBrandName;
            return name;
        }

        // GET: VehicleBrands/Create
        public ActionResult Create()
        {
            if (Session["EmpID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // POST: VehicleBrands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VehicleBrandID,VehicleBrandName")] VehicleBrand vehicleBrand)
        {
            if (ModelState.IsValid)
            {
                db.VehicleBrands.Add(vehicleBrand);
                db.SaveChanges();
                TempData["AlertMessage"] = "Vehicle brand created successfully!";
                return RedirectToAction("Index");
            }

            return View(vehicleBrand);
        }

        // GET: VehicleBrands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["EmpID"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                VehicleBrand vehicleBrand = db.VehicleBrands.Find(id);
                if (vehicleBrand == null)
                {
                    return HttpNotFound();
                }
                return View(vehicleBrand);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // POST: VehicleBrands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VehicleBrandID,VehicleBrandName")] VehicleBrand vehicleBrand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicleBrand).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AlertMessage"] = "Vehicle brand updated successfully!";
                return RedirectToAction("Index");
            }
            return View(vehicleBrand);
        }

        // GET: VehicleBrands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["EmpID"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                VehicleBrand vehicleBrand = db.VehicleBrands.Find(id);
                if (vehicleBrand == null)
                {
                    return HttpNotFound();
                }
                return View(vehicleBrand);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // POST: VehicleBrands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VehicleBrand vehicleBrand = db.VehicleBrands.Find(id);
            db.VehicleBrands.Remove(vehicleBrand);
            db.SaveChanges();
            TempData["AlertMessage"] = "Vehicle brand deleted successfully!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/VehicleBrands/Create.cshtml
@model VehicleInsurance_Employee.Models.VehicleBrand

@{
    ViewBag.Title = "Create";
}

<!-- Single pro tab review Start-->
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="pull-left">
                                        <h1>Vehicle Brand</h1>
                                    </div>
                                    <div class="pull-right">
                                        <a title="Back to list" href="@Url.Action("Index")" aria-expanded="false" class="btn btn-primary waves-effect waves-light">
                                            <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                            Back
                                        </a>
                                    </div>
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <br />
                                            <hr />
                                            @using (Html.BeginForm())
                                            {
                                                @Html.AntiForgeryToken()
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                <form action="#" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandName, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandName, new { htmlAttributes = new { @class = "form-control" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandName, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="payment-adress">
                                                                <button type="submit" class="btn btn-primary waves-effect waves-light">Create</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/VehicleBrands/Delete.cshtml
@model VehicleInsurance_Employee.Models.VehicleBrand

@{
    ViewBag.Title = "Delete";
}

<!-- Single pro tab review Start-->
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="pull-left">
                                        <h1>Vehicle Brand</h1>
                                    </div>
                                    <div class="pull-right">
                                        <a title="Back to list" href="@Url.Action("Index")" aria-expanded="false" class="btn btn-primary waves-effect waves-light">
                                            <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                            Back
                                        </a>
                                    </div>
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <br />
                                            <hr />
                                            @using (Html.BeginForm())
                                            {
                                                @Html.AntiForgeryToken()
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.VehicleBrandID)
                                                <form action="#" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandID, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandID, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandName, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandName, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="payment-adress">
                                                                <input type="submit" value="Delete" class="btn btn-primary waves-effect waves-light" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/VehicleBrands/Details.cshtml
@model VehicleInsurance_Employee.Models.VehicleBrand

@{
    ViewBag.Title = "Details";
}

<!-- Single pro tab review Start-->
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="pull-left">
                                        <h1>Vehicle Brand</h1>
                                    </div>
                                    <div class="pull-right">
                                        <a title="Back to list" href="@Url.Action("Index")" aria-expanded="false" class="btn btn-primary waves-effect waves-light">
                                            <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                            Back
                                        </a>
                                    </div>
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <br />
                                            <hr />
                                            @using (Html.BeginForm())
                                            {
                                                @Html.AntiForgeryToken()
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.VehicleBrandID)
                                                <form action="#" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandID, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandID, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandName, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandName, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            }
                                        </div>

                                        <br /><br />
                                        <h4>Vehicle Models of Vehicle Brand</h4>
                                        <hr />
                                        <table class="table" border="1">
                                            <thead>
                                                <tr>
                                                    <th scope="col">
                                                        Vehicle Model
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var d in ViewBag.VehicleModel)
                                                {
                                                    if (d.VehicleBrandID == ViewBag.VehicleBrands.VehicleBrandID)
                                                    {
                                                        <tr>
                                                            <td>@d.VehicleModelName</td>
                                                        </tr>
                                                    }
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/VehicleBrands/Edit.cshtml
@model VehicleInsurance_Employee.Models.VehicleBrand

@{
    ViewBag.Title = "Edit";
}

<!-- Single pro tab review Start-->
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="pull-left">
                                        <h1>Vehicle Brand</h1>
                                    </div>
                                    <div class="pull-right">
                                        <a title="Back to list" href="@Url.Action("Index")" aria-expanded="false" class="btn btn-primary waves-effect waves-light">
                                            <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                            Back
                                        </a>
                                    </div>
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <br />
                                            <hr />
                                            @using (Html.BeginForm())
                                            {
                                                @Html.AntiForgeryToken()
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.VehicleBrandID)
                                                <form action="#" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                    <div class="row">
                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandID, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandID, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.VehicleBrandName, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.VehicleBrandName, new { htmlAttributes = new { @class = "form-control" } })
                                                                @Html.ValidationMessageFor(model => model.VehicleBrandName, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="payment-adress">
                                                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/VehicleBrands/Index.cshtml
@model IEnumerable<VehicleInsurance_Employee.Models.VehicleBrand>

@{
    ViewBag.Title = "Index";
}

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
        <strong> @TempData["AlertMessage"]</strong>
    </div>
}

<!-- Static Table Start -->
<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sparkline13-list">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd pull-left">
                            <h1>Vehicle Brands</h1>
                        </div>
                        <div class="pull-right">
                            <a title="Create" href="@Url.Action("Create", "VehicleBrands")" aria-expanded="false" class="btn btn-custon-four btn-success">
                                <span class="fa fa-plus" aria-hidden="true"></span>
                                Create
                            </a>
                        </div>
                    </div>
                    <div class="sparkline13-graph" style="clear:both">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                   data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="vehicleBrandID">
                                            @Html.DisplayNameFor(model => model.VehicleBrandID)
                                        </th>
                                        <th data-field="vehicleBrandName">
                                            @Html.DisplayNameFor(model => model.VehicleBrandName)
                                        </th>
                                        <th data-field="action">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.VehicleBrandID)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.VehicleBrandName)
                                            </td>
                                            <td>
                                                <a title="Edit" href="@Url.Action("Edit", "VehicleBrands", new { id=item.VehicleBrandID })" aria-expanded="false" class="btn btn-custon-rounded-four btn-primary">
                                                    <span class="fa fa-edit" aria-hidden="true"></span>
                                                </a>
                                                <a title="Details" href="@Url.Action("Details", "VehicleBrands", new { id=item.VehicleBrandID })" aria-expanded="false" class="btn btn-custon-rounded-four btn-info">
                                                    <span class="fa fa-eye" aria-hidden="true"></span>
                                                </a>
                                                <a title="Delete" href="@Url.Action("Delete", "VehicleBrands", new { id=item.VehicleBrandID })" aria-expanded="false" class="btn btn-custon-rounded-four btn-danger">
                                                    <span class="fa fa-trash" aria-hidden="true"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>