VehicleInsurance_Employee/VehicleInsurance_Employee/Models/Bill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance_Employee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        [Display(Name = "Bill No")]
        public int BillNo { get; set; }

        [Display(Name = "Policy Number")]
        public int PolicyNumber { get; set; }

        [Display(Name = "Actual Datetime")]
        public Nullable<System.DateTime> ActualDatetime { get; set; }

        [Display(Name = "Expected Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ExpectedDate { get; set; }

        [Display(Name = "Amount")]
        public decimal Amount { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        public virtual OrderPolicy OrderPolicy { get; set; }
    }
}

VehicleInsurance_Employee/VehicleInsurance_Employee/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VehicleInsurance_Employee.Models;

namespace VehicleInsurance_Employee.Controllers
{
    public class BillsController : Controller
    {
        private VehicleInsuranceEntities db = new VehicleInsuranceEntities();

        // GET: Bills
        public ActionResult Index()
        {
            if (Session["EmpID"] != null)
            {
                var bills = db.Bills.Include(b => b.OrderPolicy);
                return View(bills.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // GET: Bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Bills/Create
        public ActionResult Create()
        {
            ViewBag.PolicyNumber = new SelectList(db.OrderPolicies, "PolicyNumber", "PaymentType");
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BillNo,PolicyNumber,ActualDatetime,ExpectedDate,Amount,Status")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Bills.Add(bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PolicyNumber = new SelectList(db.OrderPolicies, "PolicyNumber", "PaymentType", bill.PolicyNumber);
            return View(bill);
        }

        // GET: Bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["EmpID"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Bill bill = db.Bills.Find(id);
                if (bill == null)
                {
                    return HttpNotFound();
                }
                ViewBag.PolicyNumber = new SelectList(db.OrderPolicies, "PolicyNumber", "PaymentType", bill.PolicyNumber);
                return View(bill);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BillNo,PolicyNumber,ActualDatetime,ExpectedDate,Amount,Status")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                TempData["AlertMessage"] = "Bill updated successfully!";
                return RedirectToAction("Index");
            }
            ViewBag.PolicyNumber = new SelectList(db.OrderPolicies, "PolicyNumber", "PaymentType", bill.PolicyNumber);
            return View(bill);
        }

        // GET: Bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bill bill = db.Bills.Find(id);
            db.Bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/Bills/Create.cshtml
@model VehicleInsurance_Employee.Models.Bill

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PolicyNumber, "PolicyNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PolicyNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolicyNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActualDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActualDatetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActualDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpectedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpectedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpectedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/Bills/Delete.cshtml
@model VehicleInsurance_Employee.Models.Bill

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActualDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpectedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpectedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderPolicy.PaymentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderPolicy.PaymentType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/Bills/Details.cshtml
@model VehicleInsurance_Employee.Models.Bill

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ActualDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpectedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpectedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderPolicy.PaymentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderPolicy.PaymentType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BillNo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/Bills/Edit.cshtml
@model VehicleInsurance_Employee.Models.Bill

@{
    ViewBag.Title = "Edit";
}

<!-- Single pro tab review Start-->
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="pull-left">
                                        <h1>Bill</h1>
                                    </div>
                                    <div class="pull-right">
                                        <a title="Back to list" href="@Url.Action("Index")" aria-expanded="false" class="btn btn-primary waves-effect waves-light">
                                            <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                            Back
                                        </a>
                                    </div>
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <br />
                                            <hr />
                                            @using (Html.BeginForm())
                                            {
                                                @Html.AntiForgeryToken()
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.PolicyNumber)
                                                <form action="#" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.BillNo, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.BillNo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.BillNo, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.PolicyNumber, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.PolicyNumber, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.ActualDatetime, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.ActualDatetime, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.ActualDatetime, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.ExpectedDate, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.ExpectedDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.ExpectedDate, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                                                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                                            </div>
                                                            <div class="form-group">
                                                                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-10" })
                                                                @Html.DropDownListFor(model => model.Status, new List<SelectListItem> { new SelectListItem { Text = "Unpaid", Value = "Unpaid" }, new SelectListItem { Text = "Paid", Value = "Paid" } }, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="payment-adress">
                                                                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VehicleInsurance_Employee/VehicleInsurance_Employee/Views/Bills/Index.cshtml
@model IEnumerable<VehicleInsurance_Employee.Models.Bill>

@{
    ViewBag.Title = "Index";
}

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
        <strong> @TempData["AlertMessage"]</strong>
    </div>
}

<!-- Static Table Start -->
<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sparkline13-list">
                    <div class="sparkline13-hd">
                        <div class="sparkline13-hd">
                            <div class="main-sparkline13-hd">
                                <h1>Bills</h1>
                            </div>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                   data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="billNo">
                                            @Html.DisplayNameFor(model => model.BillNo)
                                        </th>
                                        <th data-field="policyNumber">
                                            @Html.DisplayNameFor(model => model.PolicyNumber)
                                        </th>
                                        <th data-field="actualDatetime">
                                            @Html.DisplayNameFor(model => model.ActualDatetime)
                                        </th>
                                        <th data-field="expectedDate">
                                            @Html.DisplayNameFor(model => model.ExpectedDate)
                                        </th>
                                        <th data-field="amount">
                                            @Html.DisplayNameFor(model => model.Amount)
                                        </th>
                                        <th data-field="status">
                                            @Html.DisplayNameFor(model => model.Status)
                                        </th>
                                        <th data-field="action">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.BillNo)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.PolicyNumber)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ActualDatetime)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ExpectedDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Amount)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </td>
                                            <td>
                                                <a title="Edit" href="@Url.Action("Edit", "Bills", new { id=item.BillNo })" aria-expanded="false" class="btn btn-custon-rounded-four btn-primary">
                                                    <span class="fa fa-edit" aria-hidden="true"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>